// FIX CSS WHEN STAGES > 3
// SETUP PROJECTS LIST
// FIX INITIAL DATE ERROR IN BOARD FORM (ONLY WHEN VALUE IS NOT A DATE)
// CREATE ADD TASK FUNCTION
// ADD COLOR THEME OPTION
// CREATE PROFILE COMPONENT
// FINISH NOTIFICATIONS TAB
// ADD WELCOME PAGE


// INSTEAD OF UPDATING CURRENT PROJECT RUN SETBOARDS
// AND FROM THERE UPDATE CURRENT PROJECT AND RE-SET IT WITH SETCURRENTPROJECT


// ===> Create project
// ===> POST /projects & returns project from db
// ===> Set currentProject state
// ===> On currentProject change, update state
// ===> Each time state changes update project in db