// CREATE PROFILE COMPONENT
// FINISH NOTIFICATIONS TAB
// ADD WELCOME PAGE

// ADD MORE TIME LABELS (DUE TOMORROW, DUE YESTERDAY AND MORE)
// ADD FILE UPLOAD TO TASK FORM
// ADD ONLINE/OFFLINE STATES (less than a minute ago etc...)