export const MEMBERS_ACTION_TYPES = {
    SET_MEMBERS: 'members/SET_MEMBERS',
    FETCH_MEMBERS_START: 'members/FETCH_MEMBERS_START',
    FETCH_MEMBERS_SUCCESS: 'members/FETCH_MEMBERS_SUCCESS',
    FETCH_MEMBERS_FAILED: 'members/FETCH_MEMBERS_FAILED'
}