export const MEMBERS_ACTION_TYPES = {
    SET_MEMBERS: 'members/SET_MEMBERS',
    FETCH_MEMBERS_START: 'members/FETCH_MEMBERS_START',
    FETCH_MEMBERS_SUCCESS: 'members/FETCH_MEMBERS_SUCCESS',
    FETCH_MEMBERS_FAILED: 'members/FETCH_MEMBERS_FAILED',
    FECTH_OTHER_USER_START: 'members/FECTH_OTHER_USER_START',
    FECTH_OTHER_USER_SUCCESS: 'members/FECTH_OTHER_USER_SUCCESS',
    FECTH_OTHER_USER_FAILED: 'members/FECTH_OTHER_USER_FAILED',
    SET_OTHER_USER: 'members/SET_OTHER_USER'
}