export const BOARDS_ACTION_TYPES = {
    SET_BOARDS: 'boards/SET_BOARDS',
    FETCH_BOARDS_START: 'boards/FETCH_BOARDS_START',
    FETCH_BOARDS_SUCCESS: 'boards/FETCH_BOARDS_SUCCESS',
    FETCH_BOARDS_FAILED: 'boards/FETCH_BOARDS_FAILED',
}