export const PROJECT_MEMBERS_ACTIONS_TYPES = {
    SET_PROJECT_MEMBERS: 'projectMembers/SET_PROJECT_MEMBERS',
    FETCH_PROJECT_MEMBERS_START: 'projectMembers/FETCH_PROJECT_MEMBERS_START',
    FETCH_PROJECT_MEMBERS_SUCCESS: 'projectMembers/FETCH_PROJECT_MEMBERS_SUCCESS',
    FETCH_PROJECT_MEMBERS_FAILED: 'projectMembers/FETCH_PROJECT_MEMBERS_FAILED',
}