export const CHAT_ACTION_TYPES = {
    SET_CHAT: 'chat/SET_CHAT',
    SET_CHATS: 'chat/SET_CHATS',
    // ADD_CHAT: 'chat/ADD_CHAT',
    // DELETE_CHAT: 'chat/DELETE_CHAT',
    SET_MESSAGES: 'chat/SET_MESSAGES',
    SET_CURRENT_CONTACT: 'chat/SET_CURRENT_CONTACT',
    FETCH_CHAT_START: 'chat/FETCH_CHAT_START',
    FETCH_CHAT_SUCCESS: 'chat/FETCH_CHAT_SUCCESS',
    FETCH_CHAT_FAILED: 'chat/FETCH_CHAT_FAILED',
}