export const USER_INFO_ACTION_TYPES = {
    SET_USER_INFO: 'SET_USER_INFO',
    FETCH_USER_INFO_START: 'FETCH_USER_INFO_START',
    FETCH_USER_INFO_SUCCESS: 'FETCH_USER_INFO_SUCCESS',
    FETCH_USER_INFO_FAILED: 'FETCH_USER_INFO_FAILED'
}