export const USER_INFO_ACTION_TYPES = {
    SET_USER_INFO: 'userInfo/SET_USER_INFO',
    FETCH_USER_INFO_START: 'userInfo/FETCH_USER_INFO_START',
    FETCH_USER_INFO_SUCCESS: 'userInfo/FETCH_USER_INFO_SUCCESS',
    FETCH_USER_INFO_FAILED: 'userInfo/FETCH_USER_INFO_FAILED',
    SET_IS_ADMIN: 'userInfo/SET_IS_ADMIN',
}