export const PROJECT_ACTION_TYPES = {
    SET_CURRENT_PROJECT: 'project/SET_CURRENT_PROJECT',
    UPDATE_CURRENT_PROJECT_START: 'project/UPDATE_CURRENT_PROJECT_START',
    UPDATE_CURRENT_PROJECT_SUCCESS: 'project/UPDATE_CURRENT_PROJECT_SUCCESS',
    UPDATE_CURRENT_PROJECT_FAILED: 'project/UPDATE_CURRENT_PROJECT_FAILED',
    SET_PROJECT_MEMBERS: 'project/SET_PROJECT_MEMBERS',
    SET_BOARDS: 'project/SET_BOARDS',
    ADD_ACTIVITY: 'project/ADD_ACTIVITY',
    SET_ACTIVITY: 'project/SET_ACTIVITY',
}