export const GLOBAL_STATES_ACTION_TYPES = {
    SET_ELEMENT: 'globalStates/SET_ELEMENT',
    SET_NOTIFICATION_TAB: 'globalStates/SET_NOTIFICATION_TAB',
    SET_PROFILE_TAB: 'globalStates/SET_PROFILE_TAB',
    SET_CREATE_POPUP: 'globalStates/SET_CREATE_POPUP',
    SET_STAGE: 'globalStates/SET_STAGE',
    SET_PROJECT_MENU_TAB: 'globalStates/SET_PROJECT_MENU_TAB',
    SET_ERROR_POPUP: 'globalStates/SET_ERROR_POPUP',
    SET_TASK_PRIORITY: 'globalStates/SET_TASK_PRIORITY',
    SET_ERROR: 'globalStates/SET_ERROR',
    SET_TASKS: 'globalStates/SET_TASKS',
    SET_ADMIN_PASS_FORM_OPEN: 'globalStates/SET_ADMIN_PASS_FORM_OPEN',
    SET_MOVE_TASK_POPUP_OPEN: 'globalStates/SET_MOVE_TASK_POPUP_OPEN',
    SET_NOTIFICATIONS: 'globalStates/SET_NOTIFICATIONS',
    SET_TASK_TO_MOVE: 'globalStates/SET_TASK_TO_MOVE' 
}